import Nav from './componant/Nav'
import "./globals.css"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <main>{children}</main>
      </body>
    </html>
  )
}


// import React from 'react';
// import Nav from './componant/Nav';
// import { useNavigation } from 'next/navigation'; 
// import "./globals.css";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   const { push, asPath } = useNavigation(); 
//   const isAuthenticated = false;

//   React.useEffect(() => {
//     if (!isAuthenticated && asPath !== '/sign-in') { 
//       push('/sign-in');
//     }
//   }, [isAuthenticated, asPath, push]); 

//   return (
//     <>
//       <Nav />
//       <main>{children}</main>
//     </>
//   );
// }


// import React from 'react';
// import Nav from './componant/Nav';
// import { useRouter } from 'next/navigation';
// import "./globals.css";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   const router = useRouter(); 
//   const isAuthenticated = false;



//   return (
//     <>
//       <Nav />
//       <main>{children}</main>
//     </>
//   );
// }

